### ISSUE TITLE
暫定的に設定したuser_id

### ISSUE THREAD

**Issue by MaedaRyutaro** [otTATto/TanksG#25]
### **暫定的に 設定した`user_id` **
私が作成した段階では`user_id` の値が固定値または入力値として扱われています。以下にそれをまとめます．
#### **対象ファイルと行番号**
- [ ] **Scripts/DataBase/ContactForm.cs**(お問い合わせ画面)
  - 行数: 33  
  - `form.AddField("user_id", "1"); // ユーザーIDを適宜設定`  

- [ ] **Scripts/DataBase/PresentBoxManager.cs**(プレゼント受け取り画面)
  - 行数: 17  
  -  `private int user_id = 3; // 動的に取得できる場合は設定を変更`  

---

#### **TMP_InputFieldでの `user_id` 入力**
- [ ] **Scripts/UI/StartButton.cs**  (タイトル画面)
  - 行数: 
    - **10**: `public TMP_InputField userIdInputField; // TMP_InputField（ユーザーIDの入力フィールド）`
    - **23**:
      ```csharp
      int userId;
      if (int.TryParse(userIdInputField.text, out userId))
      {
          // 取得成功時の処理
      }
      ```

**Comment by otTATto** [comment]
自分が [**b3efdd4**](https://github.com/otTATto/TanksG/commit/b3efdd4267cccdb91942694332b40efa692f1b36) で実装した方法を使えば，`TitleScene` の `Tap to Start` ボタンを押下したときにテキストボックスに入力したユーザーIDを Unity 側で保持し，他の Scene からもグローバルに扱うことができます．

この実装により，次のように書くことで，どこからでもユーザーIDを取得できます．（テキストボックスに入力していない場合はエラーになります．）
```c#
// ユーザーIDを取得
int userId = UserManager.Instance.CurrentUserID;
```

### 参考
- [**ユーザーID保持方法** - ChatGPT](https://chatgpt.com/share/67547705-bdd0-8013-b7ca-d35607e66b6f)
  - これの「方法1: グローバルに保持する (シングルトンパターン)」を参考にした

**Comment by naohitossss** [comment]
**マジックナンバー修正**
- Scripts/UI/StartButton.cs (タイトル画面)
48行を
`StartCoroutine(CheckAccountSuspended(iDDisplayer.GetPlayerID()));`
に変えた
- Scripts/DataBase/ContactForm.cs(お問い合わせ画面)
32行に
`string userID = iDDisplayer.GetPlayerID().ToString();`
を入れた
- Scripts/DataBase/PresentBoxManager.cs
58行に
`user_id = iDDisplayer.GetPlayerID();`
を入れた
