### ISSUE TITLE
BUG(#26): LoginBonusScene の画面から文字が見切れてしまう

### ISSUE THREAD

**Issue by otTATto** [otTATto/TanksG#27]
### 内容
GameMode に入ると，自分の環境では画面から文字が見切れていて上手く表示できていなかった．

### 実行環境
- Windows 11

### 再現手順
1. GameMode に入る
2. TitleScene から Start ボタンを押下して LoginBonusScene に入る
3. 画面から文字が見切れてしまっている

### スクリーンショット
![スクリーンショット (3978)](https://github.com/user-attachments/assets/20e31ba9-3b1b-4a60-a0b8-4a382c5a4a98)

### 修正すべき内容
[**このときの issue**](https://github.com/otTATto/TanksG/issues/5) と同様，[**こちらの記事**](https://mogi0506.com/unity-scale-ui/) などを参考にしながら，**16:9 Aspect** で正しく表示できるように調整をお願いします🙏

**Comment by MaedaRyutaro** [comment]
CanvasScalerを修正しても直らなかったのでDynamicCanvasScaler.csを追加してスクリプトで調整しました．また全体的に文字を小さくし，中央に寄せました．

**Comment by otTATto** [comment]
画面が正しく表示されているのを確認しました！
