### ISSUE TITLE
BUG(#26): LoginBonusScene にてログイン日数の表示がズレている

### ISSUE THREAD

**Issue by otTATto** [otTATto/TanksG#28]
### 内容
ログインボーナスを受け取ろうとすると，ログイン1日目にも関わらず  "**Login Bonus Day: 2**" と表示され，その下も **1日目～2日目まで** のアイテムが表示されます．（実際に受け取るのは **1日目のアイテムと個数** なので，その処理は問題ない．）

### 実行環境
- Windows 11

### 再現手順
1. ログイン日数 "1" の状態（初期状態）で LoginBonusScene に入る
2. "**Login Bonus Day: 2**" と表示され，その下も **1日目～2日目まで** のアイテムが表示される

### 修正すべき内容
- `laravel\blog\database\migrations\2024_12_10_162556_add_login_bonus_columns_to_game_users_table.php` を見ると `bonus_day_count` のデフォルト値が "**1**" になっていて，それは問題なさそう
- `Assets\_Completed-Assets\Scripts\DataBase\LoginBonus.cs` を見ると，1日目 ～ currentDay 日目 のアイテムを表示しているが，これが "**currentDay + 1**" **になってから** 描画処理されている気がする

**Comment by MaedaRyutaro** [comment]
StartButtonをタイトル画面で押された時点でゲームユーザーテーブルの情報が更新されDayが1加算されます．更新後のDayをloginbonusSceneで参照していたため,Dayが1多い状態を出力していました．その為,currentDayを1減らし0の時は7であるように変更しました．

**Comment by otTATto** [comment]
正しく動作するのを確認しました！✨
