### ISSUE TITLE
BUG: 画面サイズによってCanvas要素の大きさが変わってしまう

### ISSUE THREAD

**Issue by otTATto** [otTATto/TanksG#5]
### 問題の内容
- 通常の画面サイズでは問題ないが，GAME 画面を最大化すると，背景の Square が途中で見切れてしまう
### 実行環境
- Windows11
- 14 インチ，フルHD
### 再現手順
1. GAME ウィンドウを全画面表示にする
### スクリーンショット
![スクリーンショット (622)](https://github.com/user-attachments/assets/5465b1c0-0f5d-4105-8fb1-7c1aacb72958)
![スクリーンショット (623)](https://github.com/user-attachments/assets/adc19bae-5eee-4953-a9d8-303ea4efde1b)
### 修正すべき内容
**方法1**
- 単純に背景の Square のサイズを大きくする

**方法2**
- `Scale With Screen Size` モードによって，画面サイズを大きくするときに，要素の大きさも大きくする
### 参考
- [**【Unity入門】画面サイズが変わっても同じようにUIが表示されるようにする** -もぎブログ](https://mogi0506.com/unity-scale-ui/)
- [**Unityroomの画面サイズが崩れてしまう時にチェックしたほうが良いこと** - Qiita](https://qiita.com/OKUDAYUKI08/items/81e932e8295ada83055c)

**Comment by naohitossss** [comment]
画面サイズを大きくしたときに，要素の大きさも大きくなっていることがチェックできた
